#include<iostream>
#include<vector>
using namespace std;
int main()
{
	int n,len;
	cout<<"ENTER THE LENGTH OF ROD  :  ";
	cin>>len;
	cout<<"\n\nENTER THE NO OF CUTTINGS  :  ";
	cin>>n;
	cout<<endl<<endl<<"ENTER THE CUTS  :  ";
	vector<vector<int> > v(n+1,vector<int> (2));
	for(int i=1;i<=n;i++)
	{
		cin>>v[i][0];
		cin>>v[i][1];
	}
	vector<pair<int,int> > ans(len+1);
	for(int i=1;i<=len;i++)
		for(int j=1;j<=n;j++)
			if(i>=v[j][0])
			{
				if(ans[i].first<ans[i-v[j][0]].first+v[j][1])
					ans[i].second=j;
				ans[i].first=max(ans[i].first,ans[i-v[j][0]].first+v[j][1]);
			}	
	cout<<endl<<endl<<"MAXIMUM PROFIT POSSIBLE   :  "<<ans[len].first;
	cout<<endl<<endl<<"MAXIMUM PROFIT IS GENERATED BY  :  ";
	int a=len;
	vector<int> flag(n+1,0);
	while(a&&ans[a].second)
	{
		flag[ans[a].second]++;
		a-=v[ans[a].second][0];
	}
	for(int i=1;i<=n;i++)
		while(flag[i])
		{
			cout<<i<<" ";
			flag[i]--;
		}
}
