#include<iostream>
#include<vector>
using namespace std;
bool mark[1000]={0};
int ans[1000][2]={0};
int n;
int dp(int len,vector<pair<int,int> > &v)
{
	if(mark[len])
		return ans[len][0];
	if(len==0)
		return 0;
	int val;
	for(int i=1;i<=n;i++)
	{
		if(len>=v[i].first)
		{
			if(ans[len][0]<dp(len-v[i].first,v)+v[i].second)
				ans[len][1]=i;
			ans[len][0]=max(ans[len][0],v[i].second+dp(len-v[i].first,v));
		}
	}
	mark[len]=1;
	return ans[len][0];
}
int main()
{
	int len;
	cout<<"ENTER THE LENGTH OF THE ROD  :  ";
	cin>>len;
	cout<<endl<<endl<<"ENTER THE NO OF CUTTINGS  :  ";
	cin>>n;
	cout<<endl<<endl<<"ENTER THE CUTS  :  ";
	vector<pair<int,int> > v(n+1);
	for(int i=1;i<=n;i++)
	{
		cin>>v[i].first;
		cin>>v[i].second;
	}
	cout<<endl<<endl<<"MAXIMUM PROFIT POSSIBLE   :  "<<dp(len,v);
	cout<<endl<<endl<<"MAXIMUM PROFIT IS GENERATED BY  :  ";
	int a=len;
	vector<int> flag(n+1,0);
	while(a&&ans[a][1])
	{
		flag[ans[a][1]]++;
		a-=v[ans[a][1]].first;
	}
	for(int i=1;i<=n;i++)
		while(flag[i])
		{
			cout<<i<<" ";
			flag[i]--;
		}		
}
